CREATE TABLE MACMAP(
    MACPREFIX VARCHAR(6) NOT NULL,
    VENDOR VARCHAR(100) NOT NULL,
    PRIMARY KEY (MACPREFIX) 
);
PARTITION TABLE MACMAP ON COLUMN MACPREFIX;

load classes /home/vt/IdeaProjects/Collector/collector-sp.jar;
CREATE PROCEDURE 
    PARTITION ON TABLE MACMAP COLUMN MACPREFIX
    FROM CLASS com.vtorshyn.voltdb.collector.GetVendorByMACAddr;
